Repository wso2/choreo-cli, pull requests merged in 2019-10, with the labels that each got.

#57 Client API refactor
  internal/pkg/client/application_client.go
  internal/pkg/client/auth_client.go
  internal/pkg/client/client.go
Labels: Type/Improvement

#56 Impl CLI command to deploy apps
  docs/reference.md
  internal/pkg/client/application_client.go
  internal/pkg/client/client.go
  internal/pkg/cmd/application/application.go
  internal/pkg/cmd/application/deploy.go
  internal/pkg/cmd/application/deploy_test.go
  internal/pkg/cmd/runtime/context.go
  internal/pkg/test/mock/client/client.go
  internal/pkg/test/mock/runtime/context.go
  internal/pkg/test/util.go
Labels: App/Deployment

#63 Fix verbose writer getting nil issue
  cmd/choreo/choreo.go
  internal/pkg/client/client.go
Labels: bug
